
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements

language: node_js
node_js:
  - '8'
  - '7'
  - '6'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install: 'if [[ `npm -v` != 4* ]]; then npm i -g npm@4; fi'
install:
  - npm install
script: 'rm -rf node_modules && npm cache clean && npm install istanbul --silent > /dev/null 2>&1 && npm link -f --silent > /dev/null 2>&1 && npm link suman -f --silent  > /dev/null 2>&1 && suman test/src/dev/node/injection.test.js'
after_script: 'npm install -g coveralls && cat coverage/lcov.info | coveralls'
notifications:
  email: false
  slack:
    rooms:
      - sumanjs:gvauyHh80cuzpV5v8LlQOAcI#travis-ci
