language: node_js
node_js:
  - '7'
  - '6'
  - '5'
  - '4'
script: 'npm install istanbul && node cli.js --coverage test/testsrc/es5-es6/a.js'
after_script: 'npm install coveralls && cat coverage/lcov.info | ./node_modules/.bin/coveralls'
notifications:
  email: false
  slack:
    rooms:
      - sumanjs:gvauyHh80cuzpV5v8LlQOAcI#general